# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PuccaVideo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PuccaVideo

    pod 'RxSwift',    '4.2'
    pod 'RxCocoa',    '4.2'
    pod 'YouTubePlayer-Swift', '1.0'

  target 'PuccaVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PuccaVideoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
